### ISSUE TITLE
Develop a backend without depend on others

### ISSUE THREAD

**Issue by mauricioabreu** [greyblake/crystal-kiwi#2]
Yesterday I tried to test Memcached backend (after that PR was merged into crystal-memcached project) and I noticed I could not run the tests because I don't have `leveldb` installed.

Could we split the specs in order to not depend on too many backends installed on the machine? Just an idea.

**Comment by greyblake** [comment]
Yea, I guess we can do it. I'll try my idea when I'll be at home)
Thanks!

**Comment by greyblake** [comment]
Thanks for the feedback! Done in 9ade38a

Now you can run it like:
```
crystal spec ./spec/kiwi/memcached_store_spec.cr
```

**Comment by mauricioabreu** [comment]
Thanks! I was going to make it possible but you already did it! :D
